### ISSUE TITLE
Crash on Runtime

### ISSUE THREAD

**Issue by segunmicheal27** [pusher/pusher-http-java#21]
I am trying to create channel and send message to the channel on my android native application using this library but crash every time i invoke the action
Here is my error message i get:

java.lang.NoClassDefFoundError: org.apache.http.impl.client.HttpClientBuilder
                                                                at com.pusher.rest.Pusher.defaultHttpClientBuilder(Pusher.java:212)
                                                                at com.pusher.rest.Pusher.configure(Pusher.java:126)
                                                                at com.pusher.rest.Pusher.<init>(Pusher.java:103)
                                                                at com.example.MainActivity.onClick(MainActivity.java:137)
                                                                at android.view.View.performClick(View.java:4438)
                                                                at android.view.View$PerformClick.run(View.java:18422)
                                                                at android.os.Handler.handleCallback(Handler.java:733)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:136)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by zmarkan** [comment]
Hi, this is a server library and not intended to use on Android clients. Please consider using our Android library for that - `com.pusher:pusher-java-client:1.5.0` / https://github.com/pusher/pusher-websocket-java

**Comment by kn100** [comment]
Closing due to age
